version: '3.3'
services:
  mysqldb:
    container_name: weather_db
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'weather'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - ./data/sqls/init.sql:/docker-entrypoint-initdb.d/0_init.sql

  weatherApp:
    container_name: weather_app
    image: weather_app:1.0
    command: sh -c "sleep 60"
    environment:
      API_KEY: 4d31cba7ce2fa0d77446426c6394b27e
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'weather'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      LOG_LEVEL: 'INFO'
      LOG_LOCATION: '/weather_app/log'
    volumes:
      - "./.log:/weather_app/log"
    links:
      - "mysqldb:db"
    depends_on:
      - mysqldb